twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        'assets/images': images #something like a namespace for the twig paths
        'assets/css': styles
    form_themes:
        - bootstrap_4_layout.html.twig
